config/routes.rb
Rails.application.routes.draw do
  resources :constituencies
  resources :candidates do
    member do
      get "like" => "candidates#upvote"
      get "unlike" => "candidates#downvote"
    end
  end
  
  # devise_for :users
  # root 'home#index'
  get 'pages/home'
  get 'home/image'
  
  # root 'home#index'
  root to: 'candidates#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

end

app/views/shared/_image.html.erb
<h1>This portion is used to upload image</h1>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Voting Machine", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
       
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

        
        <li class="nav-item" style="align-center">
          <% Constituency.where(display_in_navbar: true).each do |con|  %>
          <%= link_to con.name, candidates_path(constituency: con.name)%>
          <% end %> 
        </li>

      
      </ul>
    </div>
  </div>
</nav>