config/routes.rb
Rails.application.routes.draw do
  resources :constituencies
  resources :candidates do
    member do
      get "like" => "candidates#upvote"
      get "unlike" => "candidates#downvote"
    end
  end
  
  # devise_for :users
  # root 'home#index'
  get 'pages/home'
  get 'home/image'
  
  # root 'home#index'
  root to: 'candidates#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

end

app/models/constituency.rb
class Constituency < ApplicationRecord
end

app/controllers/constituencies_controller.rb
class ConstituenciesController < ApplicationController
  before_action :set_constituency, only: %i[ show edit update destroy ]

  # GET /constituencies or /constituencies.json
  def index
    @constituencies = Constituency.all
  end

  # GET /constituencies/1 or /constituencies/1.json
  def show
  end

  # GET /constituencies/new
  def new
    @constituency = Constituency.new
  end

  # GET /constituencies/1/edit
  def edit
  end

  # POST /constituencies or /constituencies.json
  def create
    @constituency = Constituency.new(constituency_params)

    respond_to do |format|
      if @constituency.save
        format.html { redirect_to constituency_url(@constituency), notice: "Constituency was successfully created." }
        format.json { render :show, status: :created, location: @constituency }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituencies/1 or /constituencies/1.json
  def update
    respond_to do |format|
      if @constituency.update(constituency_params)
        format.html { redirect_to constituency_url(@constituency), notice: "Constituency was successfully updated." }
        format.json { render :show, status: :ok, location: @constituency }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituencies/1 or /constituencies/1.json
  def destroy
    @constituency.destroy

    respond_to do |format|
      format.html { redirect_to constituencies_url, notice: "Constituency was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constituency
      @constituency = Constituency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def constituency_params
      params.require(:constituency).permit(:name, :display_in_navbar)
    end
end

app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

app/views/constituencies/_constituency.html.erb
<div id="<%= dom_id constituency %>">
  <p>
    <strong>Name:</strong>
    <%= constituency.name %>
  </p>

  <p>
    <strong>Display in navbar:</strong>
    <%= constituency.display_in_navbar %>
  </p>

</div>

app/views/constituencies/_form.html.erb
<%= simple_form_for(@constituency) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :display_in_navbar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/constituencies/edit.html.erb
<h1>Editing constituency</h1>

<%= render "form", constituency: @constituency %>

<br>

<div>
  <%= link_to "Show this constituency", @constituency %> |
  <%= link_to "Back to constituencies", constituencies_path %>
</div>

app/views/constituencies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Constituencies</h1>

<div id="constituencies">
  <% @constituencies.each do |constituency| %>
    <%= render constituency %>
    <p>
      <%= link_to "Show this constituency", constituency %>
    </p>
  <% end %>
</div>

<%= link_to "New constituency", new_constituency_path %>

app/views/constituencies/new.html.erb
<h1>New constituency</h1>

<%= render "form", constituency: @constituency %>

<br>

<div>
  <%= link_to "Back to constituencies", constituencies_path %>
</div>

app/views/constituencies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @constituency %>

<div>
  <%= link_to "Edit this constituency", edit_constituency_path(@constituency) %> |
  <%= link_to "Back to constituencies", constituencies_path %>

  <%= button_to "Destroy this constituency", @constituency, method: :delete %>
</div>