config/routes.rb
Rails.application.routes.draw do
  resources :constituencies
  resources :candidates do
    member do
      get "like" => "candidates#upvote"
      get "unlike" => "candidates#downvote"
    end
  end
  
  # devise_for :users
  # root 'home#index'
  get 'pages/home'
  get 'home/image'
  
  # root 'home#index'
  root to: 'candidates#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :constituency
  acts_as_votable
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: %i[ show edit update destroy upvote downvote]

  # GET /candidates or /candidates.json
  def index
    if params.has_key?(:constituency)
      @constituency = Constituency.find_by_name(params[:constituency])
      @candidates = Candidate.where(constituency: @constituency)
    else
    @candidates = Candidate.all
    end
  end


  def upvote
    
    @candidate.upvote_from current_user
    redirect_to candidates_path
  end

  def downvote
    
    @candidate.downvote_from current_user
    redirect_to candidates_path
  end




  # GET /candidates/1 or /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates or /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to candidate_url(@candidate), notice: "Candidate was successfully created." }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1 or /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to candidate_url(@candidate), notice: "Candidate was successfully updated." }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1 or /candidates/1.json
  def destroy
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url, notice: "Candidate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def candidate_params
      params.require(:candidate).permit(:partyname, :constituency_id)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_candidate.html.erb
<div id="<%= dom_id candidate %>">
  <p>
    <strong>Partyname:</strong>
    <%= candidate.partyname %>
  </p>

  <p>
    <strong>Constituency:</strong>
    <%= candidate.constituency.name %>
  </p>

  <p>
      <%= link_to like_candidate_path(candidate), method: :get do %>
        <button type="button" class="btn btn-info" aria-label="Left-Align">
          
          Vote
          <span class="badge"><%= candidate.get_upvotes.size %></span>
          
        </button>
        <% end %>
        


         <%= link_to unlike_candidate_path(candidate), method: :get do %>
        <button type="button" class="btn btn-info" aria-label="Left-Align">
          Downvote
          <span class="badge"><%= candidate.get_upvotes.size %></span>
        </button>
        <% end %>






  </p>
   
<%# 
Used for upvotes %>

<%#   
  <%= render "candidates/upvote_link", candidate: candidate %> 

</div>

app/views/candidates/_form.html.erb
<%= simple_form_for(@candidate) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :partyname %>
    <%= f.association :constituency %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render "form", candidate: @candidate %>

<br>

<div>
  <%= link_to "Show this candidate", @candidate %> |
  <%= link_to "Back to candidates", candidates_path %>
</div>

app/views/candidates/index.html.erb
<div class="container">
    
    
     <%# if current_user.avatar.attached? %>


    <% if current_user %>
    
     
        <h1>Hello <%= current_user.email %></h1>
        <p>You are a <%= current_user.role %></p>
   
        <% if current_user.admin? %>
            There are <%= User.count %> users in the system.
<p>

           <%= link_to "Edit Account", edit_user_registration_path %>
           <br>
           <%= image_tag(current_user.avatar_thumbnail)   %>
</p>
            <p style="color: green"><%= notice %></p>

             <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete  %>

<h1>Candidates | <%= link_to "New Constituency", new_constituency_path %> | <%= link_to "Show Constituencies", constituencies_path %> </h1>
<br>
<hr>
<br>
All Constituencies <br>
<% Constituency.all.each do |con|  %>
<%= link_to con.name, candidates_path(constituency: con.name)%><br>
<% end %>
<br>




<br>
<hr>
<br>

<div id="candidates">
  <% @candidates.each do |candidate| %>
    <%= render candidate %>
    <p>
      <%= link_to "Show this candidate", candidate %>
    </p>
  <% end %>
</div>

<%= link_to "New candidate", new_candidate_path %>















            
        <% end %>
        <% if current_user.user? %>
        <p>
        You have successfully authenticated with your devise account.
        You are now ready to interact with this application.
        </p>
        
        <p>

        <%= link_to "Edit Account", edit_user_registration_path %>
        <br>
           <%= image_tag(current_user.avatar_thumbnail)   %>

        </p>

         <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete  %>
        <p style="color: green"><%= notice %></p>


<h1>Candidates </h1>

<br>
<hr>
<br>
All Constituencies <br>
<% Constituency.all.each do |con|  %>
<%= link_to con.name, candidates_path(constituency: con.name)%><br>
<% end %>
<br>




<br>
<hr>
<br>
<div id="candidates">
  <% @candidates.each do |candidate| %>
    <%= render candidate %><br><hr>
    <p>
      <%# <%= link_to "Show this candidate", candidate %>  
    </p>
  <% end %>
</div>

      <%# <%= link_to "Show this candidate", candidate %> 
    



<%# <%= link_to "New candidate", new_candidate_path %> 











        
      

        
        
        <% end %>
        <%# <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete  %> 
    <% else %>
        <h1><center>Welcome to Voting Machine</center></h1>
        <p><center>Click the button below to sign up</center></p>
        
        <div class="d-grid gap-2 col-6 mx-auto" background-color="red">
         <button class="btn btn-primary" type="button" style="background-color:white;"><%= link_to "Sign Up!", new_user_registration_path %></button>
        
        
        <br/>
       
        </div>
    <% end %>
    
  
</div>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render "form", candidate: @candidate %>

<br>

<div>
  <%= link_to "Back to candidates", candidates_path %>
</div>

app/views/candidates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @candidate %>

<div>
  <%= link_to "Edit this candidate", edit_candidate_path(@candidate) %> |
  <%= link_to "Back to candidates", candidates_path %>

  <%= button_to "Destroy this candidate", @candidate, method: :delete %>
</div>